### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by hhhmmmmmm** [DaVikingCode/UnityRuntimeSpriteSheetsGenerator#3]
Hi, could you please clarify the license? I'd like to use it in a project, but can't otherwise.

**Comment by alamboley** [comment]
Hello, it's MIT !

**Comment by hhhmmmmmm** [comment]
Yay! Could you add a License.md or License.txt file?
https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
